### ISSUE TITLE
CSV files were not saved to the same directory the .py file was located

### ISSUE THREAD

**Issue by JosephLai241** [JosephLai241/Universal-Reddit-Scraper#1]
A friend tested this scraper program on his Mac and found the CSV file saved to his home directory instead of the directory in which the program was stored.

**Comment by The-Silent-One** [comment]
If he ran the program from his home directory, he will find them there since python's open function takes the current path (pwd). It is just that the open function in the code didn't take a specific path.

**Comment by JosephLai241** [comment]
I apologize for the late reply, thank you for clarifying this for me. Closing the issue now.
