### ISSUE TITLE
Password complexity issue

### ISSUE THREAD

**Issue by bryan-campbell** [JosephLai241/Universal-Reddit-Scraper#10]
Complex passwords don't work with the authentication tokens, i had a 16 character randomly generated password from password manager which contained special characters, i was consistently receiving this error

`ERROR: invalid_grant error processing request Please recheck Reddit credentials.`

When i changed the password to a simple lowercase password, it worked instantly.

**Comment by JosephLai241** [comment]
I also use a password manager (LastPass) to generate secure passwords for my online accounts. I always make sure the password generator includes upper and lowercase letters, numbers, and symbols in the generated passwords. My Reddit password has included at least one character from all of these categories and the scraper did not give me the invalid_grant error you have posted above. 

Additionally, the PRAW docs also list this behavior [in this section](https://praw.readthedocs.io/en/v4.3.0/getting_started/authentication.html#script-application) and highlighted it in a note. It seems to be an issue with incorrectly entering your Reddit username and/or password into the script.

Are you absolutely sure you copied your password correctly?
