### ISSUE TITLE
Possible utf 8 encoding

### ISSUE THREAD

**Issue by Tudorvr** [JosephLai241/Universal-Reddit-Scraper#2]
Is it possible solving such errors when executing various searches of subreddits?

Traceback (most recent call last):
  File "reddit_scraper.py", line 288, in <module>
    main()
  File "reddit_scraper.py", line 268, in main
    write_csv(sub,cat_i,search_for,overview)
  File "reddit_scraper.py", line 231, in write_csv
    writer.writerows(zip(*overview.values()))
cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 70-71: character maps to <undefined>

**Comment by JosephLai241** [comment]
Thanks for submitting this issue. Could you be more specific as to how you came about this problem and provide the full traceback?

**Comment by Tudorvr** [comment]
Win 10, python 3.7

Full traceback:
Getting posts for r/......Market...
Sorting posts...
Traceback (most recent call last):
  File "reddit_scraper.py", line 288, in <module>
    main()
  File "reddit_scraper.py", line 268, in main
    write_csv(sub,cat_i,search_for,overview)
  File "reddit_scraper.py", line 231, in write_csv
    writer.writerows(zip(*overview.values()))
  File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>

**Comment by JosephLai241** [comment]
I apologize for the late response. I added an encoding argument in open() to ensure UTF-8 encoding. Keep me updated if you run into this issue again or if that fixed it. Thanks!

**Comment by Tudorvr** [comment]
Thank you, it's working smoothly now. problem solved
